// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var elem, outlog, run;
  elem = $(lilyturf.dom(function() {
    return this.div({
      "class": "terminal"
    }, this.div({
      "class": "glass"
    }, this.textarea({
      "class": "code"
    }), this.div({
      "class": "output"
    }, this.div({
      id: "run"
    }, this.text("Run")), this.div({
      id: "outlog"
    }))));
  }));
  $("body").append(elem);
  elem.css({
    height: "0%"
  });
  run = elem.find("#run");
  outlog = elem.find("#outlog");
  window.puts = function() {
    var key, res, that, value;
    res = [];
    for (key in arguments) {
      value = arguments[key];
      res.push(value);
    }
    that = lilyturf.dom(function() {
      return this.div({
        "class": "logline"
      }, this.text(res.join(", ")));
    });
    return outlog.prepend($(that));
  };
  run.click(function() {
    var code;
    code = elem.find(".code").val();
    return CoffeeScript["eval"](code);
  });
  exports.terminal = {
    elem: elem,
    show: function() {
      return this.elem.animate({
        height: "80%"
      });
    },
    hide: function() {
      return this.elem.animate({
        height: "0%"
      });
    }
  };
  return exports.terminal;
});
