// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var elem;
  elem = $(lilyturf.dom(function() {
    return this.div({
      "class": "config"
    }, this.div({
      "class": "options"
    }), this.div({
      "class": "control"
    }, this.div({
      "class": "button hide"
    }, this.text("hide"))));
  }));
  $("body").append(elem);
  elem.css({
    width: "0%"
  });
  elem.find(".hide").click(function() {
    return exports.config.hide();
  });
  return exports.config = {
    elem: elem,
    show: function() {
      return this.elem.animate({
        width: "28%"
      });
    },
    hide: function() {
      return this.elem.animate({
        width: "0%"
      });
    }
  };
});
