// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var elem;
  elem = $(lilyturf.dom(function() {
    return this.div({
      "class": "config"
    });
  }));
  $("body").append(elem);
  elem.css({
    width: "0%"
  });
  return exports.config = {
    elem: elem,
    show: function() {
      return this.elem.animate({
        width: "28%"
      });
    },
    hide: function() {
      return this.elem.animate({
        width: "0%"
      });
    }
  };
});
