// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var elem;
  elem = $(lilyturf.dom(function() {
    return this.div({
      "class": "program"
    }, this.div({
      "class": "control"
    }, this.div({
      "class": "button hide"
    }, this.text("hide"))), this.div({
      "class": "paper"
    }, this.text("a demo of program")));
  }));
  return exports.program = {
    elem: elem,
    place: $("#view"),
    show: function() {
      this.place.empty().append(this.elem);
      this.elem.css({
        height: "0%"
      });
      this.elem.animate({
        height: "100%"
      }, 240);
      return this.elem.find(".control .hide").click(function() {
        log("show grid");
        return window.grid.show();
      });
    }
  };
});
