// Generated by CoffeeScript 1.4.0
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

define(function(require, exports) {
  var config, data, grid, program, terminal, viewport;
  require("./extend");
  viewport = {
    width: window.innerWidth,
    height: window.innerHeight,
    update: function() {
      this.width = window.innerWidth;
      return this.height = window.innerHeight;
    },
    registry: [],
    emiter: function() {
      return this.registry.forEach(function(f) {
        return f();
      });
    },
    bind: function(callback) {
      if (__indexOf.call(this.registry, callback) < 0) {
        return registry.push(callback);
      }
    },
    drop_event: function(f) {
      return this.registry.remove(f);
    }
  };
  window.addEventListener("resize", function() {
    return viewport.update();
  });
  config = require("./config/app");
  terminal = require("./terminal/app");
  grid = require("./grid/app");
  program = require("./program/app");
  window.config = config;
  window.terminal = terminal;
  window.grid = grid;
  window.program = program;
  data = require("./data");
  grid.data = data.grid;
  return grid.show();
});
