// Generated by CoffeeScript 1.4.0
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

define(function(require, exports) {
  var config, main, terminal, viewport;
  require("./extend");
  viewport = {
    width: window.innerWidth,
    height: window.innerHeight,
    update: function() {
      this.width = window.innerWidth;
      return this.height = window.innerHeight;
    },
    registry: [],
    emiter: function() {
      return this.registry.forEach(function(f) {
        return f();
      });
    },
    bind: function(callback) {
      if (__indexOf.call(this.registry, callback) < 0) {
        return registry.push(callback);
      }
    },
    drop_event: function(f) {
      return this.registry.remove(f);
    }
  };
  window.addEventListener("resize", function() {
    return viewport.update();
  });
  terminal = require("./terminal/app");
  config = require("./config/app");
  main = {
    grid: require("./grid/app"),
    program: require("./program/app"),
    state: void 0,
    load: function(name) {}
  };
  return window.expose = {
    config: config,
    term: terminal
  };
});
